name: PathFlow
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - aiodns
  - aiohappyeyeballs
  - aiosignal
  - aom
  - arrow-cpp
  - asttokens
  - async-timeout
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - blas
  - bottleneck
  - brotlicffi
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-opencl
  - cuda-runtime
  - cuda-version
  - dav1d
  - debugpy
  - decorator
  - dill
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - filelock
  - fontconfig
  - freetype
  - fribidi
  - frozenlist
  - gflags
  - glog
  - gmp
  - gmpy2
  - gnutls
  - graphite2
  - harfbuzz
  - icu
  - idna
  - imageio
  - importlib-metadata
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - jpeg
  - jupyter_client
  - jupyter_core
  - lame
  - lazy_loader
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libavif
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcurl
  - libcusolver
  - libcusparse
  - libdeflate
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libgrpc
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libnghttp2
  - libnpp
  - libnvjitlink
  - libnvjpeg
  - libopus
  - libpng
  - libprotobuf
  - libre2-11
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libthrift
  - libtiff
  - libunistring
  - libuuid
  - libuv
  - libvpx
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - multidict
  - multiprocess
  - ncurses
  - nest-asyncio
  - nettle
  - importlib-metadata
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - jpeg
  - jupyter_client
  - jupyter_core
  - lame
  - lazy_loader
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libavif
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcurl
  - libcusolver
  - libcusparse
  - libdeflate
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libgrpc
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libnghttp2
  - libnpp
  - libnvjitlink
  - libnvjpeg
  - libopus
  - libpng
  - libprotobuf
  - libre2-11
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libthrift
  - libtiff
  - libunistring
  - libuuid
  - libuv
  - libvpx
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - multidict
  - multiprocess
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - numexpr
  - ocl-icd
  - openh264
  - openjpeg
  - openssl
  - orc
  - packaging
  - parso
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pixman
  - platformdirs
  - prompt-toolkit
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pyarrow
  - pycares
  - pycparser
  - pygments
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python-xxhash
  - pytorch
  - pytorch-cuda
  - pytorch-mutex
  - pytz
  - pyyaml
  - pyzmq
  - re2
  - readline
  - requests
  - s2n
  - scikit-image
  - scipy
  - setuptools
  - six
  - snappy
  - sqlite
  - stack_data
  - sympy
  - tbb
  - tk
  - torchaudio
  - torchtriton
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - utf8proc
  - uvloop
  - wcwidth
  - wheel
  - x264
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-xorgproto
  - xxhash
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
